#!/usr/bin/env bash
# scripts/release.sh - bump lunge versions across the monorepo.
#
# Bumps:
#   - package.json                       (root, private)
#   - crates/core/Cargo.toml             (lunge-core, [package].version)
#   - crates/core/package.json           (lunge-core)
#   - packages/mcp-server/package.json   (lunge-mcp, the published MCP server)
#   - packages/mcp-server/src/index.ts   (McpServer ctor version string)
#   - apps/web/package.json              (web, private)
#
# Does NOT touch crates/core/index.js - that file is generated by `napi build`
# and regenerated on the next build.
#
# Usage:
#   scripts/release.sh patch [--tag] [--dry-run] [--no-verify]
#   scripts/release.sh minor [--tag] [--dry-run] [--no-verify]
#   scripts/release.sh major [--tag] [--dry-run] [--no-verify]
#   scripts/release.sh --version=1.2.3 [--tag] [--dry-run] [--no-verify]
#
# Flags:
#   --tag         Commit the bump and create a git tag `vX.Y.Z`.
#   --dry-run     Print what would change; edit no files.
#   --no-verify   Skip the clean-working-tree check.
#   --publish-local  Build + publish for the current platform only (requires npm login).
#   -h, --help    Show this help.
#
# No npm publish is performed - lunge ships as a local stdio MCP server
# (see docs/install). Publishing is a separate manual step if ever needed.

set -euo pipefail

# ─── Setup ──────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT_DIR"

# Color output (disabled when not a TTY).
if [ -t 1 ]; then
  C_RESET=$'\033[0m'
  C_BOLD=$'\033[1m'
  C_RED=$'\033[31m'
  C_GREEN=$'\033[32m'
  C_YELLOW=$'\033[33m'
  C_BLUE=$'\033[34m'
  C_DIM=$'\033[2m'
else
  C_RESET=""; C_BOLD=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""; C_DIM=""
fi

log()  { printf '%s%s%s\n' "$C_BLUE" "$*" "$C_RESET" >&2; }
ok()   { printf '%s✓%s %s\n' "$C_GREEN" "$C_RESET" "$*" >&2; }
warn() { printf '%s!%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
err()  { printf '%s✗%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; }
die()  { err "$*"; exit 1; }

# ─── Args ───────────────────────────────────────────────────────────────────
BUMP=""
EXPLICIT_VERSION=""
TAG=false
DRY_RUN=false
VERIFY=true
PUBLISH_LOCAL=false

print_help() {
  sed -n '2,/^$/p' < "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

for arg in "$@"; do
  case "$arg" in
    -h|--help) print_help ;;
    patch|minor|major) BUMP="$arg" ;;
    --version=*) EXPLICIT_VERSION="${arg#--version=}" ;;
    --tag) TAG=true ;;
    --dry-run) DRY_RUN=true ;;
    --no-verify) VERIFY=false ;;
    --publish-local) PUBLISH_LOCAL=true ;;
    *) die "Unknown argument: $arg (see --help)" ;;
  esac
done

[ -n "$BUMP" ] || [ -n "$EXPLICIT_VERSION" ] || die "Missing bump type. Use: patch | minor | major | --version=X.Y.Z"
[ -z "$BUMP" ] || [ -z "$EXPLICIT_VERSION" ] || die "Pass either a bump type OR --version, not both."

# ─── Helpers ────────────────────────────────────────────────────────────────
# Read the current version from the root package.json.
current_version() {
  # Match `"version": "x.y.z"` - first occurrence only.
  grep -m1 -E '"version"[[:space:]]*:[[:space:]]*"[0-9]+\.[0-9]+\.[0-9]+"' package.json \
    | sed -E 's/.*"version"[[:space:]]*:[[:space:]]*"([0-9]+\.[0-9]+\.[0-9]+)".*/\1/'
}

# Validate a semver string (no pre-release / build metadata for simplicity).
valid_semver() {
  local v="$1"
  [[ "$v" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || return 1
}

# Bump a semver string.
bump_semver() {
  local v="$1" kind="$2"
  local major minor patch
  IFS='.' read -r major minor patch <<< "$v"
  case "$kind" in
    patch) patch=$((patch + 1)) ;;
    minor) minor=$((minor + 1)); patch=0 ;;
    major) major=$((major + 1)); minor=0; patch=0 ;;
    *) die "Invalid bump kind: $kind" ;;
  esac
  printf '%s.%s.%s' "$major" "$minor" "$patch"
}

# in-place edit that works on macOS (BSD sed) and Linux (GNU sed).
# Args: file, pattern (BRE), replacement
sed_inplace() {
  local file="$1" pattern="$2" replacement="$3"
  if [[ "$(uname)" == "Darwin" ]]; then
    sed -i '' -E "s|$pattern|$replacement|" "$file"
  else
    sed -i -E "s|$pattern|$replacement|" "$file"
  fi
}

# Replace the version field in a JSON file (first "version" occurrence).
# Args: file, new_version
set_json_version() {
  local file="$1" new="$2"
  sed_inplace "$file" \
    '("version"[[:space:]]*:[[:space:]]*)"[0-9]+\.[0-9]+\.[0-9]+"' \
    "\1\"$new\""
}

# Replace the version field in Cargo.toml ([package].version - first occurrence).
# Args: file, new_version
set_cargo_version() {
  local file="$1" new="$2"
  sed_inplace "$file" \
    '(^version[[:space:]]*=[[:space:]]*)"[0-9]+\.[0-9]+\.[0-9]+"' \
    "\1\"$new\""
}

# Replace the hardcoded version literal in the McpServer constructor.
# Args: file, new_version
set_ts_ctor_version() {
  local file="$1" new="$2"
  sed_inplace "$file" \
    '(version:[[:space:]]*)"[0-9]+\.[0-9]+\.[0-9]+"' \
    "\1\"$new\""
}

# ─── Pre-flight ─────────────────────────────────────────────────────────────
CUR="$(current_version)"
valid_semver "$CUR" || die "Root package.json has invalid version: $CUR"

if [ -n "$EXPLICIT_VERSION" ]; then
  valid_semver "$EXPLICIT_VERSION" || die "Invalid --version: $EXPLICIT_VERSION (expected X.Y.Z)"
  NEW="$EXPLICIT_VERSION"
else
  NEW="$(bump_semver "$CUR" "$BUMP")"
fi

[ "$NEW" != "$CUR" ] || die "Computed version equals current ($CUR). Nothing to do."

if $VERIFY && [ -d .git ]; then
  if ! git diff --quiet || ! git diff --cached --quiet; then
    die "Working tree has uncommitted changes. Commit or stash first, or pass --no-verify."
  fi
fi

# ─── Plan ───────────────────────────────────────────────────────────────────
FILES=(
  "package.json"
  "crates/core/Cargo.toml"
  "crates/core/package.json"
  "packages/mcp-server/package.json"
  "packages/mcp-server/src/index.ts"
  "apps/web/package.json"
)

printf '%s%sLunge release%s\n' "$C_BOLD" "$C_BLUE" "$C_RESET" >&2
printf '  %sCurrent:%s %s\n' "$C_DIM" "$C_RESET" "$CUR" >&2
printf '  %sNew:    %s %s%s%s\n' "$C_DIM" "$C_RESET" "$C_GREEN" "$NEW" "$C_RESET" >&2
printf '  %sFiles:  %s %d\n' "$C_DIM" "$C_RESET" "${#FILES[@]}" >&2
printf '  %sTag:    %s %s\n' "$C_DIM" "$C_RESET" "$($TAG && echo yes || echo no)" >&2
printf '  %sDry run:%s %s\n' "$C_DIM" "$C_RESET" "$($DRY_RUN && echo yes || echo no)" >&2
printf '\n' >&2

# ─── Bump ───────────────────────────────────────────────────────────────────
if $DRY_RUN; then
  log "Dry run - no files will be changed."
  for f in "${FILES[@]}"; do
    [ -f "$f" ] || { warn "missing: $f"; continue; }
    printf '  %s→%s %s\n' "$C_DIM" "$C_RESET" "$f" >&2
  done
  exit 0
fi

for f in "${FILES[@]}"; do
  [ -f "$f" ] || die "Missing file: $f"
done

set_json_version        "package.json"                       "$NEW"
set_cargo_version       "crates/core/Cargo.toml"             "$NEW"
set_json_version        "crates/core/package.json"           "$NEW"
set_json_version        "packages/mcp-server/package.json"   "$NEW"
set_ts_ctor_version     "packages/mcp-server/src/index.ts"   "$NEW"
set_json_version        "apps/web/package.json"              "$NEW"

# Verify each file actually contains the new version.
for f in "${FILES[@]}"; do
  if ! grep -q "$NEW" "$f"; then
    die "Bump verification failed: $NEW not found in $f"
  fi
done

ok "Bumped $CUR → $NEW across ${#FILES[@]} files."

# ─── Optional commit + tag ──────────────────────────────────────────────────
if $TAG; then
  if [ ! -d .git ]; then
    warn "Not a git repo; skipping commit + tag."
    exit 0
  fi

  git add "${FILES[@]}"
  git commit -m "chore(release): v$NEW

Bump version $CUR → $NEW across the monorepo."

  git tag -a "v$NEW" -m "lunge v$NEW"
  ok "Committed and tagged v$NEW."
  printf '%s  %sPush with:%s git push --follow-tags origin main\n' \
    "$C_DIM" "$C_RESET" "$C_RESET" >&2
  printf '%s  %s→ triggers GitHub Actions release workflow%s\n' \
    "$C_DIM" "$C_RESET" "$C_RESET" >&2
  printf '%s  %s  (builds native addons for 8 platforms + publishes lunge-core and lunge)%s\n' \
    "$C_DIM" "$C_RESET" "$C_RESET" >&2
else
  log "Files bumped. Review with: git diff"
  log "Commit + tag with: scripts/release.sh $BUMP --tag  (re-run after reverting,"
  log "  or just: git add -A && git commit -m \"chore(release): v$NEW\" && git tag v$NEW"
fi

# ─── Local publish (optional, single-platform) ──────────────────────────────
# The full cross-platform publish runs via GitHub Actions (release.yml) when
# the tag is pushed. For a local single-platform publish, use the dedicated
# scripts/publish.sh after bumping + committing:
#
#   scripts/release.sh patch --tag && git push --follow-tags origin main
#   scripts/publish.sh            # publish current platform to npm
#
# publish.sh supports --core / --mcp / --dry-run / --no-build / --otp=NNNNNN.

if $PUBLISH_LOCAL && ! $DRY_RUN; then
  warn "--publish-local is deprecated; use scripts/publish.sh instead."
  warn "Running scripts/publish.sh now..."
  exec "$SCRIPT_DIR/publish.sh"
fi
